name: Application ON Push & PR DO Code check
on: [push, pull_request]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
          
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pubspec.yaml"

      - name: Setup flutter
        if: steps.check_files.outputs.files_exists == 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Check flutter sdk version
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter --version
      
      - name: Get dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter pub get
      
      - name: Setup Dart Code Metrics
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart pub add --dev dart_code_metrics

      - name: Dart Code Metrics for lib folder
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          if [ -d lib ]
          then
            dart run dart_code_metrics:metrics analyze lib --fatal-warnings --fatal-performance --fatal-style
            dart run dart_code_metrics:metrics check-unused-files lib --fatal-unused
            dart run dart_code_metrics:metrics check-unused-code lib --fatal-unused
          else
            echo "Lib folder is not found."
          fi

      - name: Dart Code Metrics for test folder
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          if [ -d test ]
          then
            dart run dart_code_metrics:metrics analyze test --fatal-warnings --fatal-performance --fatal-style
            dart run dart_code_metrics:metrics check-unused-files test --fatal-unused
            dart run dart_code_metrics:metrics check-unused-code test --fatal-unused
          else
            echo "Test folder is not found."
          fi

      - name: Dart Code Metrics for example folder
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          if [ -d example ]
          then
            dart run dart_code_metrics:metrics analyze example --fatal-warnings --fatal-performance --fatal-style
            dart run dart_code_metrics:metrics check-unused-files example --fatal-unused
            dart run dart_code_metrics:metrics check-unused-code example --fatal-unused
          else
            echo "Example folder is not found."
          fi

      - name: Check formatting
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart format . --set-exit-if-changed

      - name: Run tests
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          # run tests if `test` folder exists
          if [ -d test ]
          then
              flutter test -r expanded
          else
              echo "Tests not found."
          fi
